#!/bin/bash

HOSTNAME="localhost"
PORT="3306"
# Sử dụng chính user Termux để tránh lỗi quyền
USERNAME=$(whoami) 
PASSWORD="123456"

DB1="ddd2_world_zh"
DB2="ddd2_account"

# Đường dẫn thư mục chứa sql trong Termux
SQL_PATH="$HOME/GunPow/sql"

# Tạo database
sql1="create database IF NOT EXISTS ${DB1} DEFAULT CHARACTER SET utf8;"
sql2="create database IF NOT EXISTS ${DB2} DEFAULT CHARACTER SET utf8;"

echo "Đang khởi tạo database..."
# Thực thi lệnh tạo database
mariadb -u${USERNAME} -p${PASSWORD} -e "${sql1}"
mariadb -u${USERNAME} -p${PASSWORD} -e "${sql2}"

# Phục hồi dữ liệu (Sửa từ /root/sql thành đường dẫn Termux)
echo "Đang import dữ liệu World..."
mariadb -u${USERNAME} -p${PASSWORD} ${DB1} < ${SQL_PATH}/ddd2_world_zh.sql

echo "Đang import dữ liệu Account..."
mariadb -u${USERNAME} -p${PASSWORD} ${DB2} < ${SQL_PATH}/ddd2_account.sql

echo "Cài đặt database kết thúc!"
sleep 0.5
